import { Link } from 'react-router-dom'
import { useState } from 'react'
import { useLanguage } from '../../context/LanguageContext'
import { useStoreCart } from '../../hooks/useStoreCart'
import { useStoreCatalog } from '../../hooks/useStoreCatalog'
import { compositionIsValid, findVariant, variantCanBeOrdered, type FiberType, type GarmentLength, type GarmentSize, type GarmentVariant, type ShopAudience, type TextileProduct } from '../../data/textileCatalog'

const words = {
  es: { eyebrow: 'Ropa andina', title: 'Elige cada prenda y luego arma tu kit', intro: 'Explora ropa de mujer, ropa de hombre y accesorios por separado. Usamos tus imágenes de referencia; los materiales, precios finales y existencias siguen pendientes.', traditional: 'Colección Andina Tradicional', premium: 'Colección Alpaca Premium', premiumText: 'Alpaca, baby alpaca y mezclas premium tendrán fichas propias cuando recibamos composición verificable, fotografías y precios del proveedor.', pending: 'Composición pendiente de confirmar', verified: 'Composición verificada', sample: 'Pendiente', all: 'Todos los materiales', alpaca: 'Alpaca', baby: 'Baby alpaca', blend: 'Mezclas con alpaca', other: 'Otras fibras', onlyVerified: 'Solo composición verificada', noResults: 'Todavía no hay prendas para este filtro.', technical: 'Ficha técnica', supplier: 'Proveedor', origin: 'Elaboración', care: 'Cuidado', price: 'Precio', size: 'Talla', length: 'Largo', color: 'Color', unavailable: 'Pendiente de disponibilidad', ask: 'Por confirmar', select: 'Selecciona una opción', note: 'No se presume 100% alpaca ni baby alpaca por el aspecto de la prenda.', allPeople: 'Todo', women: 'Mujer', men: 'Hombre', accessories: 'Accesorios', approximate: 'Precio orientativo', reference: 'Solo referencia; no disponible para compra' },
  en: { eyebrow: 'Andean clothing', title: 'Choose each piece, then build your kit', intro: 'Explore women’s clothing, men’s clothing and accessories separately. These are your supplied reference images; materials, final prices and stock are pending.', traditional: 'Traditional Andean Collection', premium: 'Premium Alpaca Collection', premiumText: 'Alpaca, baby alpaca and premium blends will have their own listings once verified composition, photos and supplier prices are available.', pending: 'Composition pending confirmation', verified: 'Composition verified', sample: 'Pending', all: 'All materials', alpaca: 'Alpaca', baby: 'Baby alpaca', blend: 'Alpaca blends', other: 'Other fibers', onlyVerified: 'Verified composition only', noResults: 'No garments match this filter yet.', technical: 'Technical details', supplier: 'Supplier', origin: 'Place of making', care: 'Care', price: 'Price', size: 'Size', length: 'Length', color: 'Color', unavailable: 'Availability pending', ask: 'To confirm', select: 'Select an option', note: 'A garment is not assumed to be 100% alpaca or baby alpaca based on appearance.', allPeople: 'All', women: 'Women', men: 'Men', accessories: 'Accessories', approximate: 'Indicative price', reference: 'Reference only; unavailable for purchase' },
  fr: { eyebrow: 'Vêtements andins', title: 'Choisissez chaque pièce pour votre kit', intro: 'Découvrez séparément les vêtements pour femmes, hommes et les accessoires. Images fournies en référence ; matières, prix finaux et stock à confirmer.', traditional: 'Collection andine traditionnelle', premium: 'Collection alpaga premium', premiumText: 'Les articles en alpaga, baby alpaga et mélanges premium auront leur propre fiche après vérification de la composition, des photos et des prix.', pending: 'Composition à confirmer', verified: 'Composition vérifiée', sample: 'En attente', all: 'Toutes les matières', alpaca: 'Alpaga', baby: 'Baby alpaga', blend: 'Mélanges avec alpaga', other: 'Autres fibres', onlyVerified: 'Composition vérifiée seulement', noResults: 'Aucun vêtement pour ce filtre actuellement.', technical: 'Fiche technique', supplier: 'Fournisseur', origin: 'Lieu de fabrication', care: 'Entretien', price: 'Prix', size: 'Taille', length: 'Longueur', color: 'Couleur', unavailable: 'Disponibilité à confirmer', ask: 'À confirmer', select: 'Choisissez une option', note: 'La présence de 100 % alpaga ou de baby alpaga ne se déduit pas de l’aspect du vêtement.', allPeople: 'Tout', women: 'Femmes', men: 'Hommes', accessories: 'Accessoires', approximate: 'Prix indicatif', reference: 'Référence uniquement ; achat indisponible' },
}

function GarmentCard({ product, t, onAdd, onPlan, exchangeRate }: { product: TextileProduct; t: typeof words.es; onAdd: (product: TextileProduct, variant: GarmentVariant) => void; onPlan: (product: TextileProduct) => void; exchangeRate: number | null }) {
  const [size, setSize] = useState<GarmentSize | null>(null)
  const [length, setLength] = useState<GarmentLength | null>(null)
  const [color, setColor] = useState('')
  const sizes = [...new Set(product.variants.map((variant) => variant.size).filter((value): value is GarmentSize => value !== null))]
  const lengths = [...new Set(product.variants.filter((variant) => !size || variant.size === size).map((variant) => variant.length).filter((value): value is GarmentLength => value !== null))]
  const colors = [...new Set(product.variants.filter((variant) => (!size || variant.size === size) && (!length || variant.length === length)).map((variant) => variant.color))]
  const variant = findVariant(product, size, length, color)
  const composition = product.composition
  const isVerified = compositionIsValid(composition)
  const canAdd = variant !== undefined && variantCanBeOrdered(product, variant)

  return <article className="overflow-hidden rounded-3xl border border-[#c9a962]/25 bg-[#f7f0e5] text-[#3a241c]">
    <div className="relative aspect-[4/5] overflow-hidden">{!product.photos.length ? <div className="flex h-full items-center justify-center bg-[#e8d8c8] px-8 text-center font-display text-xl text-[#765b4b]">{t === words.es ? 'Foto pendiente' : t === words.fr ? 'Photo en attente' : 'Photo pending'}</div> : product.photoPanel ? <div role="img" aria-label={product.name} className="h-full w-full bg-no-repeat" style={{ backgroundImage: `url(${variant?.image ?? product.photos[0]})`, backgroundSize: product.photoPanel === 'middle-third' ? '300% auto' : '200% auto', backgroundPosition: product.photoPanel === 'left-half' ? 'left top' : product.photoPanel === 'right-half' ? 'right top' : 'center top' }} /> : <img src={variant?.image ?? product.photos[0]} alt={product.name} loading="lazy" className="h-full w-full object-cover object-top" />}{!product.photoVerified && <span className="absolute bottom-3 left-3 rounded-full bg-[#3a241c]/85 px-3 py-1 text-[10px] font-semibold text-white">{t.sample}</span>}</div>
    <div className="p-5 sm:p-6">
      <h3 className="font-display text-2xl font-semibold">{product.name}</h3>
      <p className="mt-2 text-sm text-[#6d594b]">{product.description}</p>
      <p className={`mt-3 text-sm font-semibold ${isVerified ? 'text-[#4d5c37]' : 'text-[#a51f31]'}`}>{isVerified ? t.verified : t.pending}</p>
      <p className="mt-3 text-lg font-semibold">{variant?.salePricePen ? t.price : product.indicativePricePen ? t.approximate : t.price}: {variant?.salePricePen ? `S/ ${variant.salePricePen}` : product.indicativePricePen ? `≈ S/ ${product.indicativePricePen}` : t.ask}</p>
      {!variant?.salePricePen && product.indicativePricePen && <p className="text-xs text-[#765b4b]">{t.reference}{exchangeRate ? ` · ≈ US$ ${(product.indicativePricePen / exchangeRate).toFixed(2)}` : ''}</p>}
      {variant?.salePricePen && exchangeRate && <p className="text-xs text-[#765b4b]">≈ US$ {(variant.salePricePen / exchangeRate).toFixed(2)}</p>}
      {product.variants.length > 0 && <div className="mt-4 grid gap-3 sm:grid-cols-3">
        {sizes.length > 0 && <label className="text-xs">{t.size}<select value={size ?? ''} onChange={(event) => { setSize(event.target.value as GarmentSize); setLength(null); setColor('') }} className="mt-1 w-full rounded-lg border border-[#b69b7e] bg-white p-2 text-sm"><option value="">{t.select}</option>{sizes.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>}
        {lengths.length > 0 && <label className="text-xs">{t.length}<select value={length ?? ''} onChange={(event) => { setLength(event.target.value as GarmentLength); setColor('') }} className="mt-1 w-full rounded-lg border border-[#b69b7e] bg-white p-2 text-sm"><option value="">{t.select}</option>{lengths.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>}
        {colors.length > 0 && <label className="text-xs">{t.color}<select value={color} onChange={(event) => setColor(event.target.value)} className="mt-1 w-full rounded-lg border border-[#b69b7e] bg-white p-2 text-sm"><option value="">{t.select}</option>{colors.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>}
      </div>}
      <details className="mt-5 border-t border-[#b69b7e]/40 pt-4"><summary className="cursor-pointer text-sm font-semibold text-[#a51f31]">{t.technical}</summary><dl className="mt-3 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-xs"><dt>{t.supplier}</dt><dd>{product.supplier ?? t.ask}</dd><dt>{t.origin}</dt><dd>{product.verifiedOrigin ?? t.ask}</dd><dt>{t.care}</dt><dd>{product.careInstructions ?? t.ask}</dd><dt>{t.verified}</dt><dd>{isVerified ? `${composition.alpacaPercent}% alpaca${composition.otherFibers.length ? `, ${composition.otherFibers.map((fiber) => `${fiber.percent}% ${fiber.name}`).join(', ')}` : ''}` : t.pending}</dd></dl></details>
      <button type="button" disabled={!canAdd} onClick={() => { if (variant) onAdd(product, variant) }} className="mt-5 w-full rounded-full bg-[#a51f31] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{canAdd ? (t === words.es ? 'Agregar al carrito' : t === words.fr ? 'Ajouter au panier' : 'Add to cart') : t.unavailable}</button>
      {!canAdd && <button type="button" onClick={() => onPlan(product)} className="mt-2 w-full rounded-full border border-[#a51f31]/45 px-5 py-3 text-sm font-semibold text-[#a51f31]">{t === words.es ? 'Añadir a mi kit de muestra' : t === words.fr ? 'Ajouter à mon kit exemple' : 'Add to sample kit'}</button>}
    </div>
  </article>
}

export function TextileCollections({ mode = 'clothing' }: { mode?: 'clothing' | 'accessories' }) {
  const { language } = useLanguage()
  const t = words[language]
  const [audience, setAudience] = useState<ShopAudience | 'all'>('all')
  const [fiber, setFiber] = useState<FiberType | 'all'>('all')
  const [verifiedOnly, setVerifiedOnly] = useState(false)
  const { products, exchangeRatePenPerUsd: exchangeRate } = useStoreCatalog()
  const cart = useStoreCart()
  const [plannedIds, setPlannedIds] = useState<string[]>([])
  const visible = products.filter((product) => (mode === 'accessories' ? product.audience === 'accesorios' : product.audience !== 'accesorios') && (audience === 'all' || product.audience === audience) && (fiber === 'all' || product.composition.fiberType === fiber) && (!verifiedOnly || compositionIsValid(product.composition)))
  const traditional = visible.filter((product) => product.collection === 'tradicional')
  const premium = visible.filter((product) => product.collection === 'premium')
  const planned = plannedIds.map((id) => products.find((product) => product.id === id)).filter((product): product is TextileProduct => Boolean(product))
  const indicativeKitTotal = planned.every((product) => typeof product.indicativePricePen === 'number') ? planned.reduce((sum, product) => sum + (product.indicativePricePen ?? 0), 0) : null
  function addToCart(product: TextileProduct, variant: GarmentVariant) {
    if (!variantCanBeOrdered(product, variant)) return
    cart.add(product.id, variant.id, variant.stock ?? 0)
  }

  return <section id="catalogo" className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20">
    <p className="text-[11px] uppercase tracking-[0.24em] text-gold-soft">{t.eyebrow}</p><h2 className="mt-3 font-display text-4xl text-ivory sm:text-5xl">{mode === 'accessories' ? t.accessories : t.title}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-mist/75">{mode === 'accessories' ? (language === 'es' ? 'Chullos, chalinas y guantes por separado. Fotografías, materiales y disponibilidad por confirmar.' : language === 'fr' ? 'Bonnets, écharpes et gants séparément. Photos, matières et disponibilité à confirmer.' : 'Hats, scarves and gloves individually. Photos, materials and availability pending.') : t.intro}</p>
    {mode === 'clothing' && <div className="mt-7 flex flex-wrap gap-2" role="group" aria-label={language === 'es' ? 'Tipo de producto' : 'Product type'}>{([['all', t.allPeople], ['mujer', t.women], ['hombre', t.men]] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setAudience(value)} aria-pressed={audience === value} className={`rounded-full border px-4 py-2 text-sm ${audience === value ? 'border-gold bg-[#f5ede0] text-[#532b22]' : 'border-gold/30 text-ivory'}`}>{label}</button>)}</div>}
    <div className="mt-4 flex flex-wrap items-center gap-3"><select value={fiber} onChange={(event) => setFiber(event.target.value as FiberType | 'all')} aria-label={t.all} className="rounded-full border border-gold/30 bg-indigo-night px-4 py-2 text-sm text-ivory"><option value="all">{t.all}</option><option value="alpaca">{t.alpaca}</option><option value="baby-alpaca">{t.baby}</option><option value="alpaca-blend">{t.blend}</option><option value="other">{t.other}</option></select><label className="flex items-center gap-2 text-sm text-mist"><input type="checkbox" checked={verifiedOnly} onChange={(event) => setVerifiedOnly(event.target.checked)} />{t.onlyVerified}</label></div>
    <h3 className="mt-10 font-display text-3xl text-ivory">{t.traditional}</h3><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{traditional.length ? traditional.map((product) => <GarmentCard key={product.id} product={product} t={t} onAdd={addToCart} onPlan={(item) => setPlannedIds((current) => current.includes(item.id) ? current : [...current, item.id])} exchangeRate={exchangeRate} />) : <p className="text-sm text-mist/70">{t.noResults}</p>}</div>
    {mode === 'clothing' && <div className="mt-14 rounded-3xl border border-gold/35 bg-gradient-to-br from-[#2f211d] via-[#171d20] to-[#4d5c37]/40 p-7 sm:p-10"><p className="text-[11px] uppercase tracking-[0.25em] text-gold-soft">Premium</p><h3 className="mt-2 font-display text-3xl text-ivory sm:text-4xl">{t.premium}</h3><p className="mt-3 max-w-2xl text-sm leading-7 text-mist/80">{t.premiumText}</p><div className="mt-6 flex flex-wrap gap-2">{[t.alpaca, t.baby, t.blend].map((label) => <span key={label} className="rounded-full border border-gold/30 px-3 py-1.5 text-xs text-gold-soft">{label}</span>)}</div><p className="mt-5 text-xs text-mist/60">{t.note}</p></div>}
    {premium.length > 0 && <div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{premium.map((product) => <GarmentCard key={product.id} product={product} t={t} onAdd={addToCart} onPlan={(item) => setPlannedIds((current) => current.includes(item.id) ? current : [...current, item.id])} exchangeRate={exchangeRate} />)}</div>}
    <div className="mt-12 rounded-3xl border border-gold/35 bg-[#f7f0e5] p-6 text-[#3a241c] sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-[#a51f31]">{language === 'es' ? 'Combina tus favoritos' : language === 'fr' ? 'Composez votre sélection' : 'Combine your favorites'}</p><h3 className="mt-2 font-display text-3xl">{language === 'es' ? 'Mi kit de muestra' : language === 'fr' ? 'Mon kit exemple' : 'My sample kit'}</h3>{planned.length ? <><ul className="mt-5 grid gap-3 sm:grid-cols-2">{planned.map((product) => <li key={product.id} className="flex items-center gap-3 rounded-2xl bg-white p-2">{product.photos[0] ? <img src={product.photos[0]} alt="" className="h-16 w-16 rounded-xl object-cover" /> : <span className="flex h-16 w-16 items-center justify-center rounded-xl bg-[#e8d8c8] text-xs">{t.ask}</span>}<span className="min-w-0 flex-1 text-sm font-semibold">{product.name}<small className="block font-normal text-[#765b4b]">{product.indicativePricePen ? `≈ S/ ${product.indicativePricePen}` : t.ask}</small></span><button type="button" onClick={() => setPlannedIds((current) => current.filter((id) => id !== product.id))} aria-label={`${language === 'es' ? 'Quitar' : 'Remove'} ${product.name}`} className="rounded-full border px-2 py-1">×</button></li>)}</ul><p className="mt-5 font-display text-2xl">{language === 'es' ? 'Suma orientativa' : language === 'fr' ? 'Total indicatif' : 'Indicative total'}: {indicativeKitTotal === null ? t.ask : `≈ S/ ${indicativeKitTotal}`}</p>{indicativeKitTotal !== null && exchangeRate && <p className="text-sm">≈ US$ {(indicativeKitTotal / exchangeRate).toFixed(2)}</p>}<p className="mt-2 text-xs text-[#765b4b]">{language === 'es' ? 'Esta combinación no es un pedido. Precio de kit, descuento, composición y disponibilidad pendientes de confirmar.' : language === 'fr' ? 'Cette sélection ne constitue pas une commande. Prix du kit, remise, composition et disponibilité à confirmer.' : 'This selection is not an order. Kit price, discount, composition and availability require confirmation.'}</p></> : <p className="mt-3 text-sm text-[#765b4b]">{language === 'es' ? 'Añade una prenda o accesorio desde las fichas de arriba.' : language === 'fr' ? 'Ajoutez des vêtements ou accessoires depuis les fiches ci-dessus.' : 'Add clothing or accessories from the listings above.'}</p>}</div>
    <div className="mt-12 text-center"><Link to="/tienda/carrito" className="inline-flex rounded-full bg-cyan-soft px-6 py-3 text-sm font-semibold text-night">{language === 'es' ? 'Ver carrito' : language === 'fr' ? 'Voir le panier' : 'View cart'} ({cart.count})</Link></div>
  </section>
}
